# Generated by Django 3.0.8 on 2020-12-06 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.CharField(max_length=100)),
                ('image', models.ImageField(default='default.jpg', upload_to='blog_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('descrpt', models.TextField(max_length=100)),
                ('qualif', models.CharField(max_length=100)),
                ('exper', models.CharField(max_length=100)),
                ('vac', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('image1', models.ImageField(default='default.jpg', upload_to='gallery')),
                ('image2', models.ImageField(default='default.jpg', upload_to='gallery')),
                ('image3', models.ImageField(default='default.jpg', upload_to='gallery')),
                ('image4', models.ImageField(default='default.jpg', upload_to='gallery')),
                ('image5', models.ImageField(default='default.jpg', upload_to='gallery')),
            ],
        ),
    ]
