# Generated by Django 3.0.8 on 2020-12-08 04:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Envvu1', '0003_auto_20201207_1308'),
    ]

    operations = [
        migrations.CreateModel(
            name='Applynow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('qualification', models.TextField()),
                ('experiance', models.DateTimeField(default=django.utils.timezone.now)),
                ('cv', models.FileField(default='default.jpg', upload_to='CV')),
            ],
        ),
    ]
