# Generated by Django 3.0.8 on 2020-12-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Envvu1', '0004_applynow'),
    ]

    operations = [
        migrations.AddField(
            model_name='applynow',
            name='yropas',
            field=models.IntegerField(null=True),
        ),
    ]
