# Generated by Django 3.0.8 on 2020-12-08 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Envvu1', '0005_applynow_yropas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applynow',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
    ]
