# Generated by Django 3.0.8 on 2020-12-08 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Envvu1', '0007_applynow_jobtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applynow',
            name='yropas',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
