# Generated by Django 3.0.8 on 2020-12-08 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Envvu1', '0008_auto_20201208_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applynow',
            name='experiance',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='applynow',
            name='yropas',
            field=models.IntegerField(null=True),
        ),
    ]
